######################################################################
#
# File name : dds_tb_simulate.do
# Created on: Thu Sep 24 15:47:21 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.dds_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {dds_tb_wave.do}

view wave
view structure
view signals

do {dds_tb.udo}

run 1000ns
