######################################################################
#
# File name : dds_tb_wave.do
# Created on: Thu Sep 10 15:15:51 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
