######################################################################
#
# File name : dds_tb_compile.do
# Created on: Thu Sep 24 15:47:13 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\sim_tools\\modelsim2020.4\\win64\\vlib modelsim_lib/work
D:\\sim_tools\\modelsim2020.4\\win64\\vlib modelsim_lib/msim

D:\\sim_tools\\modelsim2020.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\sim_tools\\modelsim2020.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\sim_tools\\modelsim2020.4\\win64\\vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../../rtl/dds.v" \
"../../../../../rtl/dds_with_dither.v" \
"../../../../../rtl/dds_with_taylor.v" \
"../../../../../rtl/tb/dds_tb.v" \


# compile glbl module
D:\\sim_tools\\modelsim2020.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

