######################################################################
#
# File name : dds_tb.udo
# Created on: Thu Sep 10 15:15:51 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
