######################################################################
#
# File name : dss_tb_wave.do
# Created on: Thu Sep 10 14:32:53 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
